(native Math)
(native System)
(native String)

(import BigInt "big_int.scm")
(import BF "brainfuck.scm")
(import Calculator "calculator.scm")
(import Calendar "calendar.scm")
(import Church "church_encoding.scm")
(import Coroutine "coroutine.scm")
(import Fac "factorial.scm")
(import FFT "fft.scm")
(import Generator "generator.scm")
(import Interpreter "interpreter.scm")
(import List "list.scm")
(import MoB "man_or_boy.scm")
(import Quasiquote "quasiquote.scm")
(import Quickqort "quicksort.scm")
(import Quine "quine.scm")
(import Shudu "shudu.scm")
(import TheLittleSchemer "tls.scm")


(define memstat
  (lambda ()
    (define mem (System.memstat))
    (define vm_cap (get_item mem 0))
    (define vm_use (get_item mem 1))
    (define heap_cap (get_item mem 2))
    (define heap_use (get_item mem 3))
    (display "============ 内存统计 ============\n")
    (display "  总内存：") (display (/ (/ (+ vm_cap heap_cap) 1024) 1024)) (display "MiB") (newline)
    (display "    工作区容量：") (display vm_cap) (display "B") (newline)
    (display "    工作区已用：") (display (* 100 (/ vm_use vm_cap))) (display "%") (newline)
    (display "    用户区容量：") (display heap_cap) (display "B") (newline)
    (display "    用户区已用：") (display (* 100 (/ heap_use heap_cap))) (display "%") (newline)
    (display "=================================\n")))

(memstat)

(define pid (System.fork))
(if (== 0 pid) {
    (display "child process") (newline)
    (BigInt.run) (memstat)
    (BF.run) (memstat)
    (Calculator.run) (memstat)
    (Calendar.run) (memstat)
    (Church.run) (memstat)
    (Coroutine.run) (memstat)
    (Fac.run) (memstat)
    (FFT.run) (memstat)
} {
    (display "parent process") (newline)
    (Generator.run) (memstat)
    (Interpreter.run) (memstat)
    (List.run) (memstat)
    (MoB.run) (memstat)
    (Quasiquote.run) (memstat)
    (Quickqort.run) (memstat)
    (Quine.run) (memstat)
    (Shudu.run) (memstat)
    (TheLittleSchemer.run) (memstat)
})
