(native Math)
(native System)
(native String)

(import BigInt "big_int.scm")
(import BF "brainfuck.scm")
(import Calculator "calculator.scm")
(import Calendar "calendar.scm")
(import Church "church_encoding.scm")
(import Coroutine "coroutine.scm")
(import Fac "factorial.scm")
(import FFT "fft.scm")
(import Generator "generator.scm")
(import Interpreter "interpreter.scm")
(import List "list.scm")
(import MoB "man_or_boy.scm")
(import Quasiquote "quasiquote.scm")
(import Quickqort "quicksort.scm")
(import Quine "quine.scm")
(import Shudu "shudu.scm")
(import TheLittleSchemer "tls.scm")



(BigInt.run)
(BF.run)
(Calculator.run)
(Calendar.run)
(Church.run)
(Coroutine.run)
(Fac.run)
(FFT.run)
(Generator.run)
(Interpreter.run)
(List.run)
(MoB.run)
(Quasiquote.run)
(Quickqort.run)
(Quine.run)
(Shudu.run)
(TheLittleSchemer.run)

